before_install:
  - sudo wget http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
  - sudo tar zxf gdal-1.11.2.tar.gz
  - cd ./gdal-1.11.2
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..
  - git clone --depth=50 --branch=master git://github.com/OSGeo/proj.4.git
  - cd proj.4
  - sudo ./configure
  - sudo make
  - sudo make install

language: r
sudo: required

warnings_are_errors: true
