## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

sudo: false

before_install:
  - tlmgr install index

addons:
  apt:
    sources:
	- ppa:ubuntugis/ubuntugis-unstable
    packages:
    - libgdal-dev

email:
  on_success: change
  on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
