## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: r
cache: packages

r:
  - oldrel
  - release
  - devel

sudo: false

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
	- ppa:ubuntugis/ubuntugis-unstable
    packages:
    - libgdal-dev
    - libgeos-dev
